# -*- coding: utf-8 -*-
"""Jenkins.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UMBwnMiZTyZ4XXph2gBmWK9KDMf05U5M
"""

l1 = [2,4,6,8,10]

squares = [i**2 for i in l1]
print("squares of the numbers are:",squares)

cubes = [i**3 for i in l1]
print("cubes of the numbers are:",cubes)

